id: hl7.fhir.us.spl
canonical: http://hl7.org/fhir/us/spl
name: FHIR_SPL
title: SPL Mapping FHIR Implementation Guide
description: A guide that provides mapping from the FDA SPL Documents to FHIR Resources and operations.
status: draft
version: 0.1.0
fhirVersion: 5.0.0
copyrightYear: 2020+
releaseLabel: Build CI
publisher:
  name: Biomedical Research and Regulatory WG
  url: http://www.hl7.org/Special/committees/rcrim/index.cfm
jurisdiction: urn:iso:std:iso:3166#US "United States of America"

pages:
  index.md:
    title: SPL Mapping Implementation Guide Home Page
  organization.md:
    title: Organziation-Based Use Cases
  druglabel.md:
    title: Submit a Drug Label
  transforms.md:
    title: SPL / FHIR Transforms
  downloads.md:
    title: Downloads
  credits.md:
    title: Credits

menu:
  Table of Contents: toc.html
  Home Page: index.html
  Use Cases:
    Organization-Based Submissions: organization.html
    Drug Label Submission: druglabel.html
  Transforms: transforms.html
  Artifacts: artifacts.html
  Appendix:
    Downloads: downloads.html
    Credits: credits.html

parameters:
  display-warnings: true